# Generated by Django 3.0.2 on 2020-01-16 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200114_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='classroom',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.Classroom'),
        ),
    ]
