# Generated by Django 3.0.2 on 2020-01-16 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_classroom_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom_session',
            name='answers_mcq',
        ),
        migrations.AddField(
            model_name='classroom_session',
            name='answers_mcq',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cs_mca', to='core.MultipleChoiceAnswer'),
        ),
        migrations.RemoveField(
            model_name='classroom_session',
            name='answers_short',
        ),
        migrations.AddField(
            model_name='classroom_session',
            name='answers_short',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cs_as', to='core.Answers'),
        ),
        migrations.RemoveField(
            model_name='classroom_session',
            name='questions',
        ),
        migrations.AddField(
            model_name='classroom_session',
            name='questions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='csq', to='core.Questions'),
        ),
    ]
