# Generated by Django 3.0.2 on 2020-01-16 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200116_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom_session',
            name='answers_mcq',
        ),
        migrations.RemoveField(
            model_name='classroom_session',
            name='answers_short',
        ),
        migrations.RemoveField(
            model_name='classroom_session',
            name='questions',
        ),
        migrations.AddField(
            model_name='classroom_session',
            name='q_list',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
