# Generated by Django 3.0.2 on 2020-01-17 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200116_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joinedusersession',
            name='classroom',
        ),
    ]
