# Generated by Django 3.0.2 on 2020-01-17 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0013_sessionanswers'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionMarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField()),
                ('class_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ClassroomSession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
