# Generated by Django 3.0.2 on 2020-01-17 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_sessionmarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='multiplechoiceanswer',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='multiplechoiceanswer',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='multiplechoicequestions',
            name='answer',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='answer',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sessionanswers',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sessionanswers',
            name='marks',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='SessionMarks',
        ),
    ]
