# Generated by Django 3.0.2 on 2020-01-20 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200117_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionanswers',
            name='class_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='s_ans', to='core.ClassroomSession'),
        ),
    ]
